google:
  client_id: "488907415842-q5ai0g1bfg5b0gl2c3sqoilu8blitp02.apps.googleusercontent.com"
  oauth2_token_url: "https://oauth2.googleapis.com/token"
  youtube_channel_info_url: "https://www.googleapis.com/youtube/v3/channels?mine=true&part=snippet"

database:
  host: "localhost"
  port: 5432
  database_name: "yt-react-database"
  require_ssl: false

server:
  host: "localhost"
  port: 8080
  num_workers: 8