version: "3"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yt-react-database
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: always
volumes:
  dbdata:
